use HoaYeuThuong
go

CREATE OR ALTER TRIGGER TONGTIEN on CHITIETDONHANG
FOR UPDATE
AS
Begin
    update CHITIETDONHANG
    set TONGTIEN  = (
        Select SANPHAM.SP_GIABAN from SANPHAM
        where SANPHAM.SP_ID = CHITIETDONHANG.SP_ID
        ) * CHITIETDONHANG.SOLUONG
End
GO
CREATE OR ALTER TRIGGER THANHTIEN on DONHANG
FOR UPDATE
AS
BEGIN
    UPDATE DONHANG
    SET THANHTIEN = (
        SELECT SUM(CHITIETDONHANG.TONGTIEN) FROM CHITIETDONHANG
        WHERE CHITIETDONHANG.ID_DH = DONHANG.ID_DH
    ) + DONHANG.PHUPHI - DONHANG.GIAGIAM
END