use HoaYeuThuong
GO

--[DONHANG] Update: Nếu đơn hàng đã Hủy -> Hoàn tác sử dụng voucher 
update DONHANG SET VOUCHER_ID = null WHERE TINHTRANG = N'Đã hủy'
--[DONHANG] Update Thời Gian nhận hàng
update DONHANG SET THOIGIANNHANHANG = null WHERE TINHTRANG != N'Đã giao'
--[DONHANG] Update Voucher theo Ngày đặt hàng
update DONHANG SET DONHANG.VOUCHER_ID = null WHERE THOIGIANDATHANG < 
	(SELECT v.VOUCHER_VALIDATED FROM VOUCHER v WHERE v.VOUCHER_ID = DONHANG.VOUCHER_ID)

--[THANHTOAN] Update Trạng Thái Thanh Toán
DELETE FROM THANHTOAN WHERE ID_DH IN (SELECT ID_DH FROM DONHANG WHERE TINHTRANG = N'Đã hủy')
update THANHTOAN set TRANGTHAI = 0 WHERE (ID_DH IN (SELECT ID_DH FROM DONHANG WHERE TINHTRANG = N'Đang xử lí'))
	OR (ID_DH IN (SELECT ID_DH FROM DONHANG WHERE TINHTRANG = N'Đang giao') and THANHTOAN_TYPE = 0)
update THANHTOAN set TRANGTHAI = 1 WHERE (ID_DH IN (SELECT ID_DH FROM DONHANG WHERE TINHTRANG = N'Đã giao'))
	OR (ID_DH IN (SELECT ID_DH FROM DONHANG WHERE TINHTRANG = N'Đang giao') and THANHTOAN_TYPE = 1)

--[CHITIETDONHANG] Update Tổng Tiền
update CHITIETDONHANG set CHITIETDONHANG.GIABAN = (SELECT sp.SP_GIABAN FROM SANPHAM sp WHERE sp.SP_ID = CHITIETDONHANG.SP_ID)
--[CHITIETDONHANG] Update Tổng Tiền
update CHITIETDONHANG set TONGTIEN = SOLUONG * GIABAN

--[VOUCHER] Update Voucher
update VOUCHER set USED = 0
update VOUCHER set USED = 1 WHERE VOUCHER_ID IN (SELECT VOUCHER_ID FROM DONHANG)
update VOUCHER set VOUCHER_PERCENT = 5 WHERE VOUCHER_PERCENT > 0 AND VOUCHER_PERCENT < 10
update VOUCHER set VOUCHER_PERCENT = 10 WHERE VOUCHER_PERCENT > 10 AND VOUCHER_PERCENT < 15 OR VOUCHER_PERCENT = 10
update VOUCHER set VOUCHER_PERCENT = 15 WHERE VOUCHER_PERCENT > 15 AND VOUCHER_PERCENT < 20 OR VOUCHER_PERCENT = 15
update VOUCHER set VOUCHER_PERCENT = 20 WHERE VOUCHER_PERCENT > 20 OR VOUCHER_PERCENT = 20

--[DONHANG] Update Giá Giảm 
UPDATE DONHANG SET GIAGIAM = 0
UPDATE DONHANG SET DONHANG.GIAGIAM = (SELECT SUM(c.TONGTIEN) FROM CHITIETDONHANG c WHERE c.ID_DH = DONHANG.ID_DH)
	*(SELECT v.VOUCHER_PERCENT FROM VOUCHER v WHERE v.VOUCHER_ID = DONHANG.VOUCHER_ID)/100
	WHERE DONHANG.VOUCHER_ID IS not NULL	
--[DONHANG] Update Thành Tiền
UPDATE DONHANG SET DONHANG.THANHTIEN = (SELECT SUM(c.TONGTIEN) FROM CHITIETDONHANG c WHERE c.ID_DH = DONHANG.ID_DH) + DONHANG.PHUPHI - DONHANG.GIAGIAM

--SELECT * FROM DONHANG, CHITIETDONHANG WHERE DONHANG.ID_DH = 2
--SELECT SUM(TONGTIEN) FROM CHITIETDONHANG WHERE ID_DH = 15
--SELECT * FROM CHITIETDONHANG where ID_DH = 16
--SELECT * FROM VOUCHER where VOUCHER_ID = 527
--SELECT COUNT(*) FROM KHACHHANG
--SELECT * FROM SANPHAM
--SELECT SUM(c.TONGTIEN) FROM CHITIETDONHANG c WHERE c.ID_DH =15
